// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Dh8ESH-Nep_dVcHCyU0-jvHyBLwXxYo',
    appId: '1:688077635876:web:6c8ec4f03c7b051d2473b1',
    messagingSenderId: '688077635876',
    projectId: 'shopapp-5011b',
    authDomain: 'shopapp-5011b.firebaseapp.com',
    storageBucket: 'shopapp-5011b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoQ4GyUkyyh5fyLm7oDbfy_FM1pFFrh4E',
    appId: '1:688077635876:android:1f19be8ebb806d642473b1',
    messagingSenderId: '688077635876',
    projectId: 'shopapp-5011b',
    storageBucket: 'shopapp-5011b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6X5G8jsAnJuL-83mwXM3PrwMlKscSro',
    appId: '1:688077635876:ios:76b4c418155b5eb92473b1',
    messagingSenderId: '688077635876',
    projectId: 'shopapp-5011b',
    storageBucket: 'shopapp-5011b.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6X5G8jsAnJuL-83mwXM3PrwMlKscSro',
    appId: '1:688077635876:ios:76b4c418155b5eb92473b1',
    messagingSenderId: '688077635876',
    projectId: 'shopapp-5011b',
    storageBucket: 'shopapp-5011b.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Dh8ESH-Nep_dVcHCyU0-jvHyBLwXxYo',
    appId: '1:688077635876:web:99619243969054eb2473b1',
    messagingSenderId: '688077635876',
    projectId: 'shopapp-5011b',
    authDomain: 'shopapp-5011b.firebaseapp.com',
    storageBucket: 'shopapp-5011b.appspot.com',
  );
}
